#!/bin/bash
WALLET=0xa6d8e8333962cea79736b7b2811faeda6a82e3de # Change to your wallet
WORKER=Test1 # Change to your worker name

# run with Nvidia GPU
docker run -d --runtime=nvidia --rm -e WALLET=$WALLET -e WORKER=$WORKER emanaev/claymore

# to check pool stats
#  curl https://api.nanopool.org/v1/eth/avghashrateworkers/$WALLET/$WORKER
